services:
  # Banco para agendamento-service
  db-agendamento:
    image: postgres:16
    container_name: db-agendamento
    environment:
      POSTGRES_DB: agendamento_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_AGENDAMENTO_PORT:-5433}:5432"
    volumes:
      - db_agendamento_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d agendamento_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  #################################################################################
  # Banco para notificacao-service
  db-notificacao:
    image: postgres:16
    container_name: db-notificacao
    environment:
      POSTGRES_DB: notificacao_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_NOTIFICACAO_PORT:-5434}:5432"
    volumes:
      - db_notificacao_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d notificacao_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  #################################################################################
  # Banco para historico-service
  db-historico:
    image: postgres:16
    container_name: db-historico
    environment:
      POSTGRES_DB: historico_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_HISTORICO_PORT:-5435}:5432"
    volumes:
      - db_historico_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d historico_db"]
      interval: 10s
      timeout: 5s
      retries: 5



  #################################################################################
  # Banco para service-gateway
  db-gateway:
    image: postgres:16
    container_name: db-gateway
    environment:
      POSTGRES_DB: gateway_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_GATEWAY_PORT:-5436}:5432"
    volumes:
      - db_gateway_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d gateway_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço Spring Boot (exemplo: gateway)
  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"   # mapeia porta do host para a porta do container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gateway_db
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-gateway:5432/gateway_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db-gateway:
        condition: service_healthy
#################################################################################

  # RabbitMQ (com painel web)
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_agendamento_data:
  db_notificacao_data:
  db_historico_data:
  db_gateway_data:
