CREATE TABLE IF NOT EXISTS enfermeiros (
    id UUID PRIMARY KEY,
    versao BIGINT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    coren VARCHAR(15) NOT NULL UNIQUE,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE,
    ativo BOOLEAN NOT NULL
);